name: Publish Package to npmjs
on:
  push:
    branches:
      - main
jobs:

  check:
    steps:
      - name: Check if version has been updated
        id: check 
        uses: EndBug/version-check@v2
    outputs:
      result: ${{ steps.check.outputs.changed }}


  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.result == 'true' }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}